name: contrastive
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - backcall=0.1.0=py37_0
  - ca-certificates=2020.1.1=0
  - gmp=6.1.2=h6c8ec71_1
  - importlib_metadata=1.5.0=py37_0
  - ipykernel=5.1.4=py37h39e3cac_0
  - ipython=7.13.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - jedi=0.17.0=py37_0
  - jsonschema=3.2.0=py37_0
  - jupyter_client=6.1.3=py_0
  - jupyter_core=4.6.3=py37_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - markupsafe=1.1.1=py37h7b6447c_0
  - mistune=0.8.4=py37h7b6447c_0
  - nb_conda_kernels=2.2.3=py37_0
  - nbconvert=5.6.1=py37_0
  - nbformat=5.0.6=py_0
  - ncurses=6.2=he6710b0_1
  - notebook=6.0.3=py37_0
  - openssl=1.1.1g=h7b6447c_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.7.0=py_0
  - pexpect=4.8.0=py37_0
  - pickleshare=0.7.5=py37_0
  - prometheus_client=0.7.1=py_0
  - prompt-toolkit=3.0.4=py_0
  - prompt_toolkit=3.0.4=0
  - ptyprocess=0.6.0=py37_0
  - pygments=2.6.1=py_0
  - pyrsistent=0.16.0=py37h7b6447c_0
  - python=3.7.4=h265db76_1
  - pyzmq=18.1.1=py37he6710b0_0
  - readline=7.0=h7b6447c_5
  - send2trash=1.5.0=py37_0
  - setuptools=46.4.0=py37_0
  - sqlite=3.31.1=h62c20be_1
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - tk=8.6.8=hbc83047_0
  - traitlets=4.3.3=py37_0
  - wcwidth=0.1.9=py_0
  - wheel=0.34.2=py37_0
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.1=he6710b0_3
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - pytorch=1.4.0=py3.7_cuda10.1.243_cudnn7.6.3_0
  - torchvision=0.5.0=py37_cu101
  - pip:
    - absl-py==0.9.0
    - alabaster==0.7.12
    - asn1crypto==1.0.1
    - astroid==2.3.1
    - astropy==3.2.2
    - astunparse==1.6.3
    - atomicwrites==1.3.0
    - attrs==19.2.0
    - babel==2.7.0
    - backports-os==0.1.1
    - backports-shutil-get-terminal-size==1.0.0
    - beautifulsoup4==4.8.0
    - bitarray==1.0.1
    - bkcharts==0.2
    - bleach==3.1.0
    - bokeh==1.3.4
    - boto==2.49.0
    - boto3==1.12.39
    - botocore==1.15.39
    - bottleneck==1.2.1
    - cachetools==4.1.0
    - certifi==2019.9.11
    - cffi==1.12.3
    - chardet==3.0.4
    - click==7.0
    - cloudpickle==1.2.2
    - colorama==0.4.1
    - contextlib2==0.6.0
    - cryptography==2.7
    - cycler==0.10.0
    - cython==0.29.13
    - cytoolz==0.10.0
    - dask==2.5.2
    - decorator==4.4.0
    - defusedxml==0.6.0
    - distributed==2.5.2
    - docutils==0.15.2
    - dotmap==1.3.13
    - entrypoints==0.3
    - et-xmlfile==1.0.1
    - fastcache==1.1.0
    - filelock==3.0.12
    - flask==1.1.1
    - fsspec==0.5.2
    - future==0.18.2
    - gast==0.3.3
    - gevent==1.4.0
    - glob2==0.7
    - google-auth==1.15.0
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - gpustat==0.6.0
    - greenlet==0.4.15
    - grpcio==1.29.0
    - h5py==2.10.0
    - heapdict==1.0.1
    - idna==2.9
    - imageio==2.8.0
    - importlib-metadata==1.6.0
    - ipywidgets==7.5.1
    - itsdangerous==1.1.0
    - jinja2==2.10.3
    - jmespath==0.9.5
    - joblib==0.15.1
    - jupyter==1.0.0
    - jupyter-console==6.1.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.2.0
    - lazy-object-proxy==1.4.2
    - markdown==3.2.2
    - matplotlib==3.2.1
    - msgpack==0.6.1
    - mypy-extensions==0.4.3
    - networkx==2.4
    - numpy==1.17.2
    - oauthlib==3.1.0
    - opt-einsum==3.2.1
    - packaging==19.2
    - pandas==1.0.3
    - pillow==6.2.0
    - pip==20.1.1
    - protobuf==3.12.1
    - psutil==5.7.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.19
    - pyparsing==2.4.2
    - python-dateutil==2.8.0
    - pytorch-lightning==0.7.1
    - pytz==2019.3
    - pywavelets==1.1.1
    - pyyaml==5.1.2
    - qtconsole==4.7.4
    - qtpy==1.9.0
    - regex==2020.5.14
    - requests==2.23.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - s3transfer==0.3.3
    - sacremoses==0.0.43
    - scikit-image==0.17.2
    - scikit-learn==0.23.1
    - scipy==1.4.1
    - seaborn==0.10.1
    - sentencepiece==0.1.91
    - six==1.12.0
    - sklearn==0.0
    - sortedcontainers==2.1.0
    - soupsieve==1.9.3
    - tblib==1.4.0
    - tensorboard==2.2.1
    - tensorboard-plugin-wit==1.6.0.post3
    - tensorflow==2.2.0
    - tensorflow-estimator==2.2.0
    - termcolor==1.1.0
    - threadpoolctl==2.0.0
    - tifffile==2020.6.3
    - tokenizers==0.7.0
    - toolz==0.10.0
    - torch-dct==0.1.5
    - torchfields==0.0.5
    - torchtext==0.6.0
    - tornado==6.0.3
    - tqdm==4.46.0
    - transformers==2.10.0
    - typed-argument-parser==1.4.3
    - typed-ast==1.4.1
    - typing-extensions==3.7.4.2
    - typing-inspect==0.6.0
    - urllib3==1.24.2
    - webencodings==0.5.1
    - werkzeug==0.16.0
    - widgetsnbextension==3.5.1
    - wrapt==1.11.2
    - zict==1.0.0
